import { Game } from '../src/models/game.model'

export const FAKE_GAME: Game = {
	gameCreation: 1641637443000,
	gameDuration: 1352,
	gameEndTimestamp: 1641638851492,
	gameId: 4169212699,
	gameMode: 'ARAM',
	gameName: 'teambuilder-match-4169212699',
	gameStartTimestamp: 1641637498566,
	gameType: 'MATCHED_GAME',
	gameVersion: '12.1.416.4011',
	mapId: 12,
	participants: [
		{
			assists: 36,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 24780,
			champLevel: 18,
			championId: 25,
			championName: 'Morgana',
			championTransform: 0,
			consumablesPurchased: 2,
			damageDealtToBuildings: 2055,
			damageDealtToObjectives: 2055,
			damageDealtToTurrets: 2055,
			damageSelfMitigated: 10485,
			deaths: 8,
			detectorWardsPlaced: 0,
			doubleKills: 1,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: true,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 15555,
			goldSpent: 14650,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 1,
			inhibitorsLost: 0,
			item0: 6653,
			item1: 2420,
			item2: 4637,
			item3: 3089,
			item4: 3116,
			item5: 3020,
			item6: 2052,
			itemsPurchased: 17,
			killingSprees: 4,
			kills: 11,
			lane: 'TOP',
			largestCriticalStrike: 0,
			largestKillingSpree: 3,
			largestMultiKill: 2,
			longestTimeSpentLiving: 233,
			magicDamageDealt: 70908,
			magicDamageDealtToChampions: 35095,
			magicDamageTaken: 12765,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 0,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 1,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5002,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8128,
								var1: 2695,
								var2: 35,
								var3: 0,
							},
							{
								perk: 8126,
								var1: 1471,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8135,
								var1: 2705,
								var2: 5,
								var3: 0,
							},
						],
						style: 8100,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8009,
								var1: 7037,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8014,
								var1: 870,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
				],
			},
			physicalDamageDealt: 3520,
			physicalDamageDealtToChampions: 1024,
			physicalDamageTaken: 9095,
			profileIcon: 5182,
			puuid: 'clXphhSDW8AGxmROUmj3fSd1ob7dyuMAF6ijzPuuGcZrwLAnCN7FKmtLsZDeIemwMOdVNiSETvncWw',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SUPPORT',
			sightWardsBoughtInGame: 0,
			spell1Casts: 60,
			spell2Casts: 81,
			spell3Casts: 25,
			spell4Casts: 9,
			summoner1Casts: 3,
			summoner1Id: 4,
			summoner2Casts: 11,
			summoner2Id: 32,
			summonerId: 'vaTOjEHc1kYWDl6ml9-JRl-Ks9rBMHXTJFJa-ajEoL1A-oI',
			summonerLevel: 310,
			summonerName: 'SparrowNox',
			teamEarlySurrendered: false,
			teamId: 100,
			teamPosition: '',
			timeCCingOthers: 90,
			timePlayed: 1352,
			totalDamageDealt: 76405,
			totalDamageDealtToChampions: 38095,
			totalDamageShieldedOnTeammates: 2742,
			totalDamageTaken: 26027,
			totalHeal: 5894,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 54,
			totalTimeCCDealt: 155,
			totalTimeSpentDead: 230,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 1976,
			trueDamageDealtToChampions: 1976,
			trueDamageTaken: 4166,
			turretKills: 2,
			turretTakedowns: 3,
			turretsLost: 1,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: true,
		},
		{
			assists: 19,
			baronKills: 0,
			bountyLevel: 5,
			champExperience: 25249,
			champLevel: 18,
			championId: 23,
			championName: 'Tryndamere',
			championTransform: 0,
			consumablesPurchased: 1,
			damageDealtToBuildings: 3113,
			damageDealtToObjectives: 3113,
			damageDealtToTurrets: 3113,
			damageSelfMitigated: 37902,
			deaths: 8,
			detectorWardsPlaced: 0,
			doubleKills: 6,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 18753,
			goldSpent: 16450,
			individualPosition: 'Invalid',
			inhibitorKills: 1,
			inhibitorTakedowns: 2,
			inhibitorsLost: 0,
			item0: 6696,
			item1: 1053,
			item2: 6675,
			item3: 3006,
			item4: 3031,
			item5: 6671,
			item6: 2052,
			itemsPurchased: 23,
			killingSprees: 7,
			kills: 28,
			lane: 'MIDDLE',
			largestCriticalStrike: 904,
			largestKillingSpree: 5,
			largestMultiKill: 5,
			longestTimeSpentLiving: 410,
			magicDamageDealt: 1281,
			magicDamageDealtToChampions: 1281,
			magicDamageTaken: 18650,
			neutralMinionsKilled: 0,
			nexusKills: 1,
			nexusLost: 0,
			nexusTakedowns: 1,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 2,
			pentaKills: 1,
			perks: {
				statPerks: {
					defense: 5002,
					flex: 5008,
					offense: 5005,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8008,
								var1: 52,
								var2: 16,
								var3: 0,
							},
							{
								perk: 9111,
								var1: 2474,
								var2: 470,
								var3: 0,
							},
							{
								perk: 9104,
								var1: 6,
								var2: 40,
								var3: 0,
							},
							{
								perk: 8299,
								var1: 2919,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8143,
								var1: 990,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8106,
								var1: 5,
								var2: 0,
								var3: 0,
							},
						],
						style: 8100,
					},
				],
			},
			physicalDamageDealt: 105197,
			physicalDamageDealtToChampions: 43859,
			physicalDamageTaken: 14599,
			profileIcon: 5024,
			puuid: 'IgD-qDPF9TcIrYT6GyI1wx5AEkTzjlGW1XtiSevi_wECmWC6RI_96632-9HzS3aUHA8r_l7pCMh3NQ',
			quadraKills: 1,
			riotIdName: '',
			riotIdTagline: '',
			role: 'CARRY',
			sightWardsBoughtInGame: 0,
			spell1Casts: 36,
			spell2Casts: 31,
			spell3Casts: 69,
			spell4Casts: 7,
			summoner1Casts: 4,
			summoner1Id: 4,
			summoner2Casts: 18,
			summoner2Id: 32,
			summonerId: 'KGdSu6vsUGZL9SlVrfvXNmLa09wzU7ZnI6NtWSxjBqrsUl8',
			summonerLevel: 271,
			summonerName: 'spicyhothot',
			teamEarlySurrendered: false,
			teamId: 100,
			teamPosition: '',
			timeCCingOthers: 7,
			timePlayed: 1352,
			totalDamageDealt: 107549,
			totalDamageDealtToChampions: 46211,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 35438,
			totalHeal: 10434,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 77,
			totalTimeCCDealt: 44,
			totalTimeSpentDead: 262,
			totalUnitsHealed: 1,
			tripleKills: 3,
			trueDamageDealt: 1071,
			trueDamageDealtToChampions: 1071,
			trueDamageTaken: 2188,
			turretKills: 1,
			turretTakedowns: 2,
			turretsLost: 1,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: true,
		},
		{
			assists: 35,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 23308,
			champLevel: 18,
			championId: 1,
			championName: 'Annie',
			championTransform: 0,
			consumablesPurchased: 1,
			damageDealtToBuildings: 1892,
			damageDealtToObjectives: 1892,
			damageDealtToTurrets: 1892,
			damageSelfMitigated: 9028,
			deaths: 11,
			detectorWardsPlaced: 0,
			doubleKills: 1,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: false,
			firstTowerAssist: true,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 13768,
			goldSpent: 13235,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 0,
			item0: 6653,
			item1: 4637,
			item2: 3158,
			item3: 3116,
			item4: 3003,
			item5: 1052,
			item6: 2052,
			itemsPurchased: 19,
			killingSprees: 1,
			kills: 6,
			lane: 'MIDDLE',
			largestCriticalStrike: 0,
			largestKillingSpree: 3,
			largestMultiKill: 2,
			longestTimeSpentLiving: 181,
			magicDamageDealt: 41046,
			magicDamageDealtToChampions: 24378,
			magicDamageTaken: 19620,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 0,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 3,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5002,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8128,
								var1: 1483,
								var2: 27,
								var3: 0,
							},
							{
								perk: 8126,
								var1: 920,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8106,
								var1: 5,
								var2: 0,
								var3: 0,
							},
						],
						style: 8100,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8009,
								var1: 3795,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8014,
								var1: 786,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
				],
			},
			physicalDamageDealt: 3677,
			physicalDamageDealtToChampions: 938,
			physicalDamageTaken: 5794,
			profileIcon: 4855,
			puuid: 'iI1Bb6J3FprYZ7De0Yi3MMHql2mhHQ4cfusM0z0hW71Noow7fnkJqb_LZYw4kA3F9i0FaWZ7tkn1cw',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SUPPORT',
			sightWardsBoughtInGame: 0,
			spell1Casts: 44,
			spell2Casts: 28,
			spell3Casts: 18,
			spell4Casts: 71,
			summoner1Casts: 5,
			summoner1Id: 4,
			summoner2Casts: 7,
			summoner2Id: 7,
			summonerId: 'dqPnt5WW0jFQEABEfy16OwtQWpbQi-lwAjVukKndwUF_V6va',
			summonerLevel: 41,
			summonerName: 'Wholesome0ne',
			teamEarlySurrendered: false,
			teamId: 100,
			teamPosition: '',
			timeCCingOthers: 19,
			timePlayed: 1352,
			totalDamageDealt: 49524,
			totalDamageDealtToChampions: 26172,
			totalDamageShieldedOnTeammates: 855,
			totalDamageTaken: 26871,
			totalHeal: 3433,
			totalHealsOnTeammates: 667,
			totalMinionsKilled: 22,
			totalTimeCCDealt: 161,
			totalTimeSpentDead: 324,
			totalUnitsHealed: 4,
			tripleKills: 0,
			trueDamageDealt: 4801,
			trueDamageDealtToChampions: 856,
			trueDamageTaken: 1455,
			turretKills: 1,
			turretTakedowns: 2,
			turretsLost: 1,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: true,
		},
		{
			assists: 39,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 22703,
			champLevel: 18,
			championId: 30,
			championName: 'Karthus',
			championTransform: 0,
			consumablesPurchased: 5,
			damageDealtToBuildings: 0,
			damageDealtToObjectives: 0,
			damageDealtToTurrets: 0,
			damageSelfMitigated: 10632,
			deaths: 16,
			detectorWardsPlaced: 0,
			doubleKills: 1,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 14862,
			goldSpent: 14350,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 0,
			item0: 6653,
			item1: 4637,
			item2: 3020,
			item3: 3135,
			item4: 3089,
			item5: 0,
			item6: 2052,
			itemsPurchased: 24,
			killingSprees: 1,
			kills: 9,
			lane: 'TOP',
			largestCriticalStrike: 0,
			largestKillingSpree: 3,
			largestMultiKill: 2,
			longestTimeSpentLiving: 95,
			magicDamageDealt: 81728,
			magicDamageDealtToChampions: 40602,
			magicDamageTaken: 21854,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 0,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 4,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5002,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8124,
								var1: 97,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8126,
								var1: 1028,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8135,
								var1: 2648,
								var2: 5,
								var3: 0,
							},
						],
						style: 8100,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8009,
								var1: 4701,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8299,
								var1: 3515,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
				],
			},
			physicalDamageDealt: 809,
			physicalDamageDealtToChampions: 403,
			physicalDamageTaken: 7699,
			profileIcon: 4899,
			puuid: 'Ux2W6cDIBYrWOFNk_hV7m70NogZF4an5GSKx2zgT0pRuDchcaz4QYvcIVUM1dg547AomuES7mP8FUA',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'DUO',
			sightWardsBoughtInGame: 0,
			spell1Casts: 319,
			spell2Casts: 44,
			spell3Casts: 32,
			spell4Casts: 9,
			summoner1Casts: 1,
			summoner1Id: 4,
			summoner2Casts: 0,
			summoner2Id: 32,
			summonerId: 'NbZHL06Ce7WhTeU43qRXQYtFp1tRIwj30sob1_WpZkxfjcs',
			summonerLevel: 72,
			summonerName: 'Evilmilkjug',
			teamEarlySurrendered: false,
			teamId: 100,
			teamPosition: '',
			timeCCingOthers: 32,
			timePlayed: 1352,
			totalDamageDealt: 83326,
			totalDamageDealtToChampions: 41794,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 32345,
			totalHeal: 751,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 60,
			totalTimeCCDealt: 432,
			totalTimeSpentDead: 374,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 788,
			trueDamageDealtToChampions: 788,
			trueDamageTaken: 2791,
			turretKills: 0,
			turretTakedowns: 0,
			turretsLost: 1,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: true,
		},
		{
			assists: 31,
			baronKills: 0,
			bountyLevel: 2,
			champExperience: 25813,
			champLevel: 18,
			championId: 103,
			championName: 'Ahri',
			championTransform: 0,
			consumablesPurchased: 2,
			damageDealtToBuildings: 953,
			damageDealtToObjectives: 953,
			damageDealtToTurrets: 953,
			damageSelfMitigated: 8985,
			deaths: 5,
			detectorWardsPlaced: 0,
			doubleKills: 2,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 15419,
			goldSpent: 13250,
			individualPosition: 'Invalid',
			inhibitorKills: 1,
			inhibitorTakedowns: 2,
			inhibitorsLost: 0,
			item0: 3157,
			item1: 3145,
			item2: 3102,
			item3: 3040,
			item4: 6655,
			item5: 3158,
			item6: 2052,
			itemsPurchased: 15,
			killingSprees: 4,
			kills: 11,
			lane: 'TOP',
			largestCriticalStrike: 0,
			largestKillingSpree: 3,
			largestMultiKill: 2,
			longestTimeSpentLiving: 327,
			magicDamageDealt: 48619,
			magicDamageDealtToChampions: 19705,
			magicDamageTaken: 11663,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 0,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 5,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5002,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8128,
								var1: 1840,
								var2: 30,
								var3: 0,
							},
							{
								perk: 8126,
								var1: 938,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8106,
								var1: 5,
								var2: 0,
								var3: 0,
							},
						],
						style: 8100,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8210,
								var1: 26,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8236,
								var1: 48,
								var2: 0,
								var3: 0,
							},
						],
						style: 8200,
					},
				],
			},
			physicalDamageDealt: 2502,
			physicalDamageDealtToChampions: 471,
			physicalDamageTaken: 5372,
			profileIcon: 3789,
			puuid: 'mZPVb6tyaXTxzYXD0CGnczbwyvqHASWmfYhWa_eFeeUJ19PjVztzzZYm4-svlVNoIq9IpNAI4juCgw',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SUPPORT',
			sightWardsBoughtInGame: 0,
			spell1Casts: 88,
			spell2Casts: 54,
			spell3Casts: 54,
			spell4Casts: 39,
			summoner1Casts: 8,
			summoner1Id: 7,
			summoner2Casts: 5,
			summoner2Id: 4,
			summonerId:
				'hcr0ZPPg222HI7UWstvWkRk7ClLHjOJ7-U_MEKwYOEvz4Dt6OwlP0lJmhQ',
			summonerLevel: 219,
			summonerName: 'bababababoo',
			teamEarlySurrendered: false,
			teamId: 100,
			teamPosition: '',
			timeCCingOthers: 30,
			timePlayed: 1352,
			totalDamageDealt: 68326,
			totalDamageDealtToChampions: 28852,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 18434,
			totalHeal: 6933,
			totalHealsOnTeammates: 886,
			totalMinionsKilled: 36,
			totalTimeCCDealt: 77,
			totalTimeSpentDead: 142,
			totalUnitsHealed: 5,
			tripleKills: 0,
			trueDamageDealt: 17204,
			trueDamageDealtToChampions: 8675,
			trueDamageTaken: 1399,
			turretKills: 0,
			turretTakedowns: 1,
			turretsLost: 1,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: true,
		},
		{
			assists: 25,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 20944,
			champLevel: 18,
			championId: 20,
			championName: 'Nunu',
			championTransform: 0,
			consumablesPurchased: 0,
			damageDealtToBuildings: 0,
			damageDealtToObjectives: 0,
			damageDealtToTurrets: 0,
			damageSelfMitigated: 55497,
			deaths: 17,
			detectorWardsPlaced: 0,
			doubleKills: 0,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: true,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 14787,
			goldSpent: 14400,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 2,
			item0: 3020,
			item1: 4629,
			item2: 3083,
			item3: 3068,
			item4: 3065,
			item5: 3076,
			item6: 2052,
			itemsPurchased: 31,
			killingSprees: 2,
			kills: 9,
			lane: 'MIDDLE',
			largestCriticalStrike: 0,
			largestKillingSpree: 2,
			largestMultiKill: 1,
			longestTimeSpentLiving: 140,
			magicDamageDealt: 51797,
			magicDamageDealtToChampions: 23228,
			magicDamageTaken: 35169,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 1,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 6,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5001,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8229,
								var1: 2499,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8226,
								var1: 250,
								var2: 361,
								var3: 0,
							},
							{
								perk: 8210,
								var1: 27,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8236,
								var1: 48,
								var2: 0,
								var3: 0,
							},
						],
						style: 8200,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8105,
								var1: 13,
								var2: 5,
								var3: 0,
							},
						],
						style: 8100,
					},
				],
			},
			physicalDamageDealt: 4400,
			physicalDamageDealtToChampions: 1704,
			physicalDamageTaken: 18392,
			profileIcon: 4881,
			puuid: 'ck5y8HlsosBOJ8IvM3lU_-h68e5jJIJw1Oa1T97wAQg9JRYCppcpNxGILp_KAqLSXKU3mW9gxTwd_g',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SUPPORT',
			sightWardsBoughtInGame: 0,
			spell1Casts: 50,
			spell2Casts: 70,
			spell3Casts: 104,
			spell4Casts: 14,
			summoner1Casts: 10,
			summoner1Id: 14,
			summoner2Casts: 29,
			summoner2Id: 32,
			summonerId: 'Vr9V4-jVmLtrTmrDT--MHvuUpb4iv17_Y-nyv0-d-5-w0TQh',
			summonerLevel: 137,
			summonerName: 'NicoleLovesMusic',
			teamEarlySurrendered: false,
			teamId: 200,
			teamPosition: '',
			timeCCingOthers: 48,
			timePlayed: 1352,
			totalDamageDealt: 76585,
			totalDamageDealtToChampions: 27963,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 57379,
			totalHeal: 10935,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 46,
			totalTimeCCDealt: 187,
			totalTimeSpentDead: 418,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 20387,
			trueDamageDealtToChampions: 3030,
			trueDamageTaken: 3817,
			turretKills: 0,
			turretTakedowns: 0,
			turretsLost: 4,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: false,
		},
		{
			assists: 20,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 21546,
			champLevel: 18,
			championId: 86,
			championName: 'Garen',
			championTransform: 0,
			consumablesPurchased: 0,
			damageDealtToBuildings: 553,
			damageDealtToObjectives: 553,
			damageDealtToTurrets: 553,
			damageSelfMitigated: 86132,
			deaths: 12,
			detectorWardsPlaced: 0,
			doubleKills: 0,
			dragonKills: 0,
			firstBloodAssist: true,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 14440,
			goldSpent: 12650,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 2,
			item0: 3111,
			item1: 3075,
			item2: 3065,
			item3: 6662,
			item4: 3110,
			item5: 3801,
			item6: 2052,
			itemsPurchased: 19,
			killingSprees: 1,
			kills: 9,
			lane: 'MIDDLE',
			largestCriticalStrike: 17,
			largestKillingSpree: 2,
			largestMultiKill: 1,
			longestTimeSpentLiving: 168,
			magicDamageDealt: 13825,
			magicDamageDealtToChampions: 3212,
			magicDamageTaken: 31735,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 1,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 7,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5001,
					flex: 5008,
					offense: 5007,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8437,
								var1: 1426,
								var2: 1092,
								var3: 0,
							},
							{
								perk: 8401,
								var1: 308,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8444,
								var1: 2344,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8451,
								var1: 285,
								var2: 0,
								var3: 0,
							},
						],
						style: 8400,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 9103,
								var1: 13,
								var2: 50,
								var3: 0,
							},
							{
								perk: 8017,
								var1: 0,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
				],
			},
			physicalDamageDealt: 36325,
			physicalDamageDealtToChampions: 9255,
			physicalDamageTaken: 13591,
			profileIcon: 4903,
			puuid: '-ezYn-k39TSn42zD7a2NcewPStW18C9sOQSEhU8wtYR3_L47fZOViqCnOxCO8QN3ogdT03JDeO8aQA',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SUPPORT',
			sightWardsBoughtInGame: 0,
			spell1Casts: 64,
			spell2Casts: 43,
			spell3Casts: 51,
			spell4Casts: 11,
			summoner1Casts: 11,
			summoner1Id: 21,
			summoner2Casts: 7,
			summoner2Id: 4,
			summonerId: 'jzbq0gSuHosYXo4yk1oi0Cs432As65H-0xyaIG2qZuuVi_iY',
			summonerLevel: 111,
			summonerName: '0NevErOddOrEveN0',
			teamEarlySurrendered: false,
			teamId: 200,
			teamPosition: '',
			timeCCingOthers: 31,
			timePlayed: 1352,
			totalDamageDealt: 56711,
			totalDamageDealtToChampions: 19028,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 50096,
			totalHeal: 4288,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 27,
			totalTimeCCDealt: 718,
			totalTimeSpentDead: 304,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 6561,
			trueDamageDealtToChampions: 6561,
			trueDamageTaken: 4769,
			turretKills: 0,
			turretTakedowns: 1,
			turretsLost: 4,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: false,
		},
		{
			assists: 17,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 25506,
			champLevel: 18,
			championId: 63,
			championName: 'Brand',
			championTransform: 0,
			consumablesPurchased: 0,
			damageDealtToBuildings: 0,
			damageDealtToObjectives: 0,
			damageDealtToTurrets: 0,
			damageSelfMitigated: 8828,
			deaths: 10,
			detectorWardsPlaced: 0,
			doubleKills: 2,
			dragonKills: 0,
			firstBloodAssist: true,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 14074,
			goldSpent: 13700,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 2,
			item0: 3040,
			item1: 1026,
			item2: 6653,
			item3: 3020,
			item4: 3089,
			item5: 1011,
			item6: 2052,
			itemsPurchased: 16,
			killingSprees: 2,
			kills: 8,
			lane: 'BOTTOM',
			largestCriticalStrike: 0,
			largestKillingSpree: 3,
			largestMultiKill: 2,
			longestTimeSpentLiving: 378,
			magicDamageDealt: 89130,
			magicDamageDealtToChampions: 24454,
			magicDamageTaken: 16085,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 1,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 8,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5001,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8229,
								var1: 2634,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8226,
								var1: 250,
								var2: 546,
								var3: 0,
							},
							{
								perk: 8210,
								var1: 10,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8236,
								var1: 48,
								var2: 0,
								var3: 0,
							},
						],
						style: 8200,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8105,
								var1: 13,
								var2: 5,
								var3: 0,
							},
						],
						style: 8100,
					},
				],
			},
			physicalDamageDealt: 3318,
			physicalDamageDealtToChampions: 266,
			physicalDamageTaken: 8654,
			profileIcon: 839,
			puuid: 'DREr7Uyvjw4p41EbJYXeOBc6Ais65WQNerBW34vfqFNe5ZQx7dZOzy5BLzfNKeELYuRUXVr4V1RpdA',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SOLO',
			sightWardsBoughtInGame: 0,
			spell1Casts: 69,
			spell2Casts: 61,
			spell3Casts: 46,
			spell4Casts: 10,
			summoner1Casts: 2,
			summoner1Id: 13,
			summoner2Casts: 2,
			summoner2Id: 4,
			summonerId: 'enawDySCULRIjAHU2TN7lBv2f8REgIZPP-SRGi4EPB9saJWf',
			summonerLevel: 64,
			summonerName: 'DanNumberTwo',
			teamEarlySurrendered: false,
			teamId: 200,
			teamPosition: '',
			timeCCingOthers: 6,
			timePlayed: 1352,
			totalDamageDealt: 92898,
			totalDamageDealtToChampions: 25170,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 26221,
			totalHeal: 3276,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 61,
			totalTimeCCDealt: 23,
			totalTimeSpentDead: 258,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 449,
			trueDamageDealtToChampions: 449,
			trueDamageTaken: 1482,
			turretKills: 0,
			turretTakedowns: 0,
			turretsLost: 4,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: false,
		},
		{
			assists: 14,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 22088,
			champLevel: 18,
			championId: 145,
			championName: 'Kaisa',
			championTransform: 0,
			consumablesPurchased: 2,
			damageDealtToBuildings: 1501,
			damageDealtToObjectives: 1501,
			damageDealtToTurrets: 1501,
			damageSelfMitigated: 14496,
			deaths: 12,
			detectorWardsPlaced: 0,
			doubleKills: 0,
			dragonKills: 0,
			firstBloodAssist: true,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 16815,
			goldSpent: 14450,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 2,
			item0: 6655,
			item1: 3020,
			item2: 4628,
			item3: 3115,
			item4: 3135,
			item5: 1058,
			item6: 2052,
			itemsPurchased: 18,
			killingSprees: 3,
			kills: 16,
			lane: 'MIDDLE',
			largestCriticalStrike: 0,
			largestKillingSpree: 4,
			largestMultiKill: 1,
			longestTimeSpentLiving: 289,
			magicDamageDealt: 57456,
			magicDamageDealtToChampions: 32434,
			magicDamageTaken: 17173,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 1,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 9,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5002,
					flex: 5008,
					offense: 5008,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8128,
								var1: 2167,
								var2: 26,
								var3: 0,
							},
							{
								perk: 8139,
								var1: 1400,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8138,
								var1: 30,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8135,
								var1: 2519,
								var2: 5,
								var3: 0,
							},
						],
						style: 8100,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8009,
								var1: 3829,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8014,
								var1: 1597,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
				],
			},
			physicalDamageDealt: 32096,
			physicalDamageDealtToChampions: 6128,
			physicalDamageTaken: 9688,
			profileIcon: 3786,
			puuid: 'kCy5RuQXJtj6gtjyxmIdh4qh8NqX5wa1NLuoC5CUjmboxRqk-IY5CVZVhntxFFyFgaeGl2v80rWuGw',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'DUO',
			sightWardsBoughtInGame: 0,
			spell1Casts: 82,
			spell2Casts: 81,
			spell3Casts: 63,
			spell4Casts: 7,
			summoner1Casts: 8,
			summoner1Id: 6,
			summoner2Casts: 3,
			summoner2Id: 13,
			summonerId: 'ZCS1-WOmrM_-cwP0BEitDIZcmYOOEFzZKjitzokUrHe4GV0',
			summonerLevel: 521,
			summonerName: 'Captain Woowoo',
			teamEarlySurrendered: false,
			teamId: 200,
			teamPosition: '',
			timeCCingOthers: 0,
			timePlayed: 1352,
			totalDamageDealt: 89698,
			totalDamageDealtToChampions: 38708,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 28469,
			totalHeal: 2238,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 70,
			totalTimeCCDealt: 0,
			totalTimeSpentDead: 323,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 145,
			trueDamageDealtToChampions: 145,
			trueDamageTaken: 1608,
			turretKills: 1,
			turretTakedowns: 1,
			turretsLost: 4,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: false,
		},
		{
			assists: 13,
			baronKills: 0,
			bountyLevel: 0,
			champExperience: 18649,
			champLevel: 18,
			championId: 166,
			championName: 'Akshan',
			championTransform: 0,
			consumablesPurchased: 2,
			damageDealtToBuildings: 48,
			damageDealtToObjectives: 48,
			damageDealtToTurrets: 48,
			damageSelfMitigated: 14855,
			deaths: 14,
			detectorWardsPlaced: 0,
			doubleKills: 0,
			dragonKills: 0,
			firstBloodAssist: false,
			firstBloodKill: false,
			firstTowerAssist: false,
			firstTowerKill: false,
			gameEndedInEarlySurrender: false,
			gameEndedInSurrender: false,
			goldEarned: 13026,
			goldSpent: 12400,
			individualPosition: 'Invalid',
			inhibitorKills: 0,
			inhibitorTakedowns: 0,
			inhibitorsLost: 2,
			item0: 3184,
			item1: 3042,
			item2: 3006,
			item3: 6676,
			item4: 3046,
			item5: 6670,
			item6: 2052,
			itemsPurchased: 19,
			killingSprees: 1,
			kills: 6,
			lane: 'MIDDLE',
			largestCriticalStrike: 417,
			largestKillingSpree: 2,
			largestMultiKill: 1,
			longestTimeSpentLiving: 150,
			magicDamageDealt: 2302,
			magicDamageDealtToChampions: 1224,
			magicDamageTaken: 20899,
			neutralMinionsKilled: 0,
			nexusKills: 0,
			nexusLost: 1,
			nexusTakedowns: 0,
			objectivesStolen: 0,
			objectivesStolenAssists: 0,
			participantId: 10,
			pentaKills: 0,
			perks: {
				statPerks: {
					defense: 5001,
					flex: 5008,
					offense: 5005,
				},
				styles: [
					{
						description: 'primaryStyle',
						selections: [
							{
								perk: 8021,
								var1: 1801,
								var2: 1293,
								var3: 0,
							},
							{
								perk: 9101,
								var1: 2131,
								var2: 2221,
								var3: 0,
							},
							{
								perk: 9103,
								var1: 16,
								var2: 40,
								var3: 0,
							},
							{
								perk: 8014,
								var1: 498,
								var2: 0,
								var3: 0,
							},
						],
						style: 8000,
					},
					{
						description: 'subStyle',
						selections: [
							{
								perk: 8139,
								var1: 1518,
								var2: 0,
								var3: 0,
							},
							{
								perk: 8135,
								var1: 875,
								var2: 5,
								var3: 0,
							},
						],
						style: 8100,
					},
				],
			},
			physicalDamageDealt: 39246,
			physicalDamageDealtToChampions: 13752,
			physicalDamageTaken: 9493,
			profileIcon: 4878,
			puuid: '-YxiQDai-gKV6201s2AVtWDrZ2xVpSXRWO1g9DTkI5K7Cuwoda6pR0odGNzbUd1nsvvgoTFJI2Ubsw',
			quadraKills: 0,
			riotIdName: '',
			riotIdTagline: '',
			role: 'SUPPORT',
			sightWardsBoughtInGame: 0,
			spell1Casts: 52,
			spell2Casts: 20,
			spell3Casts: 24,
			spell4Casts: 2,
			summoner1Casts: 1,
			summoner1Id: 4,
			summoner2Casts: 0,
			summoner2Id: 13,
			summonerId: '66ujdEtHIqsQbUzbkJsd7FKwkr1yxKcHQ77cHLCRdAamct4',
			summonerLevel: 621,
			summonerName: 'Dozing Dionysus',
			teamEarlySurrendered: false,
			teamId: 200,
			teamPosition: '',
			timeCCingOthers: 0,
			timePlayed: 1352,
			totalDamageDealt: 62514,
			totalDamageDealtToChampions: 15792,
			totalDamageShieldedOnTeammates: 0,
			totalDamageTaken: 32081,
			totalHeal: 3594,
			totalHealsOnTeammates: 0,
			totalMinionsKilled: 40,
			totalTimeCCDealt: 0,
			totalTimeSpentDead: 352,
			totalUnitsHealed: 1,
			tripleKills: 0,
			trueDamageDealt: 20965,
			trueDamageDealtToChampions: 815,
			trueDamageTaken: 1688,
			turretKills: 0,
			turretTakedowns: 0,
			turretsLost: 4,
			unrealKills: 0,
			visionScore: 0,
			visionWardsBoughtInGame: 0,
			wardsKilled: 0,
			wardsPlaced: 0,
			win: false,
		},
	],
	platformId: 'NA1',
	queueId: 450,
	teams: [
		{
			bans: [],
			objectives: {
				baron: {
					first: false,
					kills: 0,
				},
				champion: {
					first: false,
					kills: 65,
				},
				dragon: {
					first: false,
					kills: 0,
				},
				inhibitor: {
					first: true,
					kills: 2,
				},
				riftHerald: {
					first: false,
					kills: 0,
				},
				tower: {
					first: true,
					kills: 4,
				},
			},
			teamId: 100,
			win: true,
		},
		{
			bans: [],
			objectives: {
				baron: {
					first: false,
					kills: 0,
				},
				champion: {
					first: true,
					kills: 48,
				},
				dragon: {
					first: false,
					kills: 0,
				},
				inhibitor: {
					first: false,
					kills: 0,
				},
				riftHerald: {
					first: false,
					kills: 0,
				},
				tower: {
					first: false,
					kills: 1,
				},
			},
			teamId: 200,
			win: false,
		},
	],
	tournamentCode: '',
}
